### ISSUE TITLE
Keeping up to date

### ISSUE THREAD

**Issue by Lukas-Batema** [theopcoder/PedestriaBotOfficial#7]
Dear @theopcoder,
I recently noticed that this repository's release is at [v1.0.0](https://github.com/theopcoder/PedestriaBotOfficial/releases/tag/v1.0.0).  This is different than the version the  [2.0.0 Changelog Line 91](https://github.com/theopcoder/PedestriaBotOfficial/blob/47b43c3879ad50f951f4fe7a2c0136fc8641e3eb/Changelogs/2.0.0%20Changelog#L91) says. That line says it is currently at 2.1.2, which was the "Grammar Fix." I know that because I created the [PR](https://github.com/theopcoder/PedestriaBotOfficial/pull/4) for that release. I would recommend keeping up to date with the tags and release titles in the release section of the GitHub Site on this repository. In my opinion, you should create a release for every release that comes out, eg. v2.0.0, v3.0.0, v4.0.0, etc.; or a prerelease for other updates, eg. v2.1.3, v3.1.4, v2.0.1, v2.1.0, etc. If you have any questions, just drop a comment down below! Thanks!

Best Wishes,
Lukas Batema

**Comment by theopcoder** [comment]
This is because I don't release versions until it is complete. Although I will start making new releases.

**Comment by Lukas-Batema** [comment]
> This is because I don't release versions until it is complete. Although I will start making new releases.

Dear @theopcoder,
Thanks for the info. I still think that you can create the release after you publicly release the update though, don't you think?

Best Wishes,
Lukas Batema

**Comment by theopcoder** [comment]
Once we get the pull request all set up, I will start creating a release and updating it to the new versions. Thank you for informing me and have a great day!
